# Generated by Django 5.1.6 on 2025-03-02 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug_alter_post_trumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trumbnail',
            field=models.ImageField(blank=True, default='images/thumbnails/site.png', upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'webp', 'jpeg', 'gif'])], verbose_name='Фотографии поста'),
        ),
    ]
